version: '3.8'

volumes:
  mysql_data:

services:
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment: 
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=snippetbox
      - MYSQL_USER=web
      - MYSQL_PASSWORD=pass
    volumes:
      - mysql_data:/var/lib/mysql